account_holder_name = input("Enter account holder name: ")
account_number = int(input("Enter account number: "))
opening_balance = int(input("Enter opening balance: "))
withdrawal_1 = int(input("Enter withdrawal amount 1 : "))
balance_after_withdrawal_1 = opening_balance - withdrawal_1
deposit_1 = int(input("Enter deposot amount 1 : "))
balance_after_deposit_1 = balance_after_withdrawal_1 + deposit_1
interest_credit = int(input("Enter interest : "))
balance_after_interest_credit = balance_after_deposit_1 + interest_credit
deposit_2 =  int(input("Enter deposit amount 2 : "))
balance_after_deposit_2 = balance_after_interest_credit + deposit_2
withdrawal_2 = int(input("Enter withdrawal amount 2 : "))
balance_after_withdrawal_2 = balance_after_deposit_2 - withdrawal_2
closing_balance = balance_after_withdrawal_2

print("\nAccount Holder Name =",account_holder_name)
print("Account Number =",account_number)
print("\nOpening Balance =",opening_balance)
print("\nWithdrawal Amount 1 =",withdrawal_1)
print("Balance after withdrawal 1 =",balance_after_withdrawal_1)
print("\nDeposit Amount 1 =",deposit_1)
print("Balance after deposit 1 =",balance_after_deposit_1)
print("\nInterest Credit =",interest_credit)
print("Balance after interest credit =",balance_after_interest_credit)
print("\nDeposit Amount 2 =",deposit_2)
print("Balance after deposit 2 =",balance_after_deposit_2)
print("\nWithdrawal Amount 2 =",withdrawal_2)
print("Balance after withdrawal 2 =",balance_after_withdrawal_2)
print("\nClosing Balance =",closing_balance)