day_1_date = input("Enter day 1 date : ")
day_1_city = input("Enter day 1 city name : ")
day_1_place = input("Enter day 1 place name : ")
day_1_activity = input("Enter day 1 activity : ")
cost_for_day_1 = int(input("Enter day 1 cost : "))
day_2_date = input("Enter day 2 date : ")
day_2_city = input("Enter day 2 city : ")
day_2_place = input("Enter day 2 place : ")
day_2_activity = input("Enter day 2 activity : ")
cost_for_day_2 = int(input("Enter day 2 cost : "))
day_3_date = input("Enter day 3 date : ")
day_3_city = input("Enter day 3 city : ")
day_3_place = input("Enter day 3 place : ")
day_3_activity = input("Enetr day 3 activity : ")
cost_for_day_3 = int(input("Enter day 3 cost : "))
total_cost_for_3_days = cost_for_day_1 + cost_for_day_2 + cost_for_day_3

print("\nWelcome To ABC Tours")
print("\nTravel Plan")
print("\nDay 1 Date : ",day_1_date)
print("Day 1 City : ",day_1_city)
print("Day 1 Place : ",day_1_place)
print("Day 1 Activity : ",day_1_activity)
print("Cost For Day 1 : ",cost_for_day_1)

print("\nDay 2 Date : ",day_2_date)
print("Day 2 City : ",day_2_city)
print("Day 2 Place : ",day_2_place)
print("Day 2 Activity : ",day_2_activity)
print("Cost For Day 2 : ",cost_for_day_2)

print("\nDay 3 Date : ",day_3_date)
print("Day 3 city : ",day_3_city)
print("Day 3 Place : ",day_3_place)
print("Day 3 Activity : ",day_3_activity)
print("Cost For Day 3 : ",cost_for_day_3)

print("\nTotal Cost : ",total_cost_for_3_days)
print("\nThank You")